FROM python:3.12-slim

WORKDIR /LoadDataMicroservice

COPY LoadDataMicroservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY LoadDataMicroservice .

CMD ["python", "main.py"]
