FROM python:3.12-slim

WORKDIR /GetterMicroservice

COPY GetterMicroservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./GetterMicroservice .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]


