FROM python:3.12-slim

WORKDIR /ValidationMicroservice

COPY ValidationMicroservice/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY /ValidationMicroservice .

CMD ["python3", "main.py"]


